apache/pekko-connectors-kafka

- build.sbt
relates to https://github.com/apache/incubator-pekko/issues/15
> remove mima checks

- .github/workflows/link-validator.yml
- build.sbt
relates to https://github.com/apache/incubator-pekko-connectors-kafka/actions/runs/3474817556/jobs/5808394670
> scalafmt issue in build.sbt

- LICENSE
- NOTICE
- build.sbt
- project/MetaInfLicenseNoticeCopy.scala
* based on what is in incubator-pekko repo
> add license and notice to jars

- .github/workflows/link-validator.yml
* fails when the yml is entirely commented out
* https://github.com/apache/incubator-pekko-connectors-kafka/actions/runs/4095791912
> enable some of link-validator job

- .github/workflows/check-build-test.yml
copied from https://github.com/FasterXML/jackson-module-scala/blob/2.15/.github/workflows/ci.yml#L21
> try to limit this one concurrent run per PR

- project/ProjectSettings.scala
- project/plugins.sbt
Replaces ci-release with dynver, see https://lists.apache.org/thread/l7yp8yb2ooy7opwmzpw7hkmz9gm0qr2r
> Replace ci-release with dynver

- project/Versions.scala
Necessary for https://github.com/apache/incubator-pekko-projection/pull/19
> Update pekko snapshot version

- .github/workflows/publish-nightly.yml
Needed for https://github.com/apache/incubator-pekko-projection/pull/19
> Allow manual trigger for nightly publish

- .github/workflows/check-build-test.yml
- .github/workflows/headers.yml
Necessary to add github workflow check
> Split header check into its own GitHub workflow

- project/Dependencies.scala
- project/Versions.scala
follow up to https://github.com/apache/incubator-pekko/pull/273
> upgrade jackson to 2.14.2

- docs/src/main/paradox/snapshots.md
- project/ResolverSettings.scala
- project/build.properties
Latest version of sbt now has Apache snapshots repo already included
> Use ApacheMavenSnapshotsRepo constant

- .github/actions/sync-nightlies/action.yml
- .github/workflows/publish-nightly.yml
- CONTRIBUTING.md
- core/src/main/scala/org/apache/pekko/kafka/javadsl/PartitionAssignmentHandler.scala
- core/src/main/scala/org/apache/pekko/kafka/scaladsl/PartitionAssignmentHandler.scala
- testkit/src/main/scala/org/apache/pekko/kafka/testkit/scaladsl/KafkaSpec.scala
- tests/src/test/scala/org/apache/pekko/kafka/internal/CommitCollectorStageSpec.scala
- tests/src/test/scala/org/apache/pekko/kafka/internal/CommittingProducerSinkSpec.scala
- tests/src/test/scala/org/apache/pekko/kafka/internal/ConsumerResetProtectionSpec.scala
Also set up nightly doc publish
> some remaining Akka naming issues

- docs/src/main/paradox/index.md
- project/ParadoxSettings.scala
- project/plugins.sbt
> fix up note about naming

- .github/workflows/check-build-test.yml
- project/Versions.scala
Pekko core has upgraded already
> use Scala 3.3.0

- project/Versions.scala
- scripts/link-validator.conf
> Update Scala 2 versions

- project/Versions.scala
this is basically the RC1 code for Pekko
> use latest pekko snapshot

- build.sbt
- legal/PekkoKafkaNotice.txt
- legal/StandardLicense.txt
- project/AddMetaInfLicenseFiles.scala
> acknowledge use of Kafka derived code

- project/Dependencies.scala
- project/ParadoxSettings.scala
- project/Versions.scala
matches what is used in pekko core
> standardise on scalatest 3.2.14

- core/src/main/scala/org/apache/pekko/kafka/internal/TransactionalSources.scala
- core/src/main/scala/org/apache/pekko/kafka/javadsl/MetadataClient.scala
- tests/src/test/scala/docs/scaladsl/FetchMetadata.scala
- tests/src/test/scala/org/apache/pekko/kafka/ConsumerSettingsSpec.scala
- tests/src/test/scala/org/apache/pekko/kafka/ProducerSettingsSpec.scala
- tests/src/test/scala/org/apache/pekko/kafka/internal/ProducerSpec.scala
This is mainly to prepare the project for Scala 3 for when we make the compiler flags more strict
> Add type annotations to implicits

- project/AddMetaInfLicenseFiles.scala
- project/build.properties
relates to https://github.com/apache/incubator-pekko/pull/474
> use standard ASL header on new files

- build.sbt
- project/ResolverSettings.scala
- project/Versions.scala
- project/plugins.sbt
* also includes https://github.com/apache/incubator-pekko/pull/468
> pekko 1.0.0

- .github/workflows/link-validator.yml
- docs/src/main/paradox/home.md
- project/ParadoxSettings.scala
- project/Versions.scala
- scripts/link-validator.conf
we validate the doc links in our main Pekko repositories
> run link validator

- docs/src/main/paradox/release-notes/index.md
based on https://cwiki.apache.org/confluence/display/PEKKO/Pekko+Connectors+Kafka+Release+Notes
> release notes 1.0.0

- NOTICE
* remove duplicate stmt about ASF
* I don't think this is part of the reason for the -1 vote (which I think is just about the signing check)
see https://lists.apache.org/thread/x0wybd9gkgnqxgc42wstnx42oj9xmm7l
> Update NOTICE (duplicate stmt about ASF)

- docs/src/main/paradox/home.md
- project/Dependencies.scala
- project/LicenseReport.scala
- project/ParadoxSettings.scala
- project/plugins.sbt
- scripts/link-validator.conf
> Add sbt-license-report

- build.sbt
- project/build.properties
SBT 1.9.5. added the `Resolver.ApacheMavenStagingRepo` constant
> Update to SBT 1.9.6 and use Apache Staging repo constant

- project/Dependencies.scala
https://github.com/qos-ch/logback/issues/745
> logback cve

- NOTICE
- legal/PekkoKafkaNotice.txt
see https://github.com/apache/incubator-pekko/pull/1009
> add incubating to NOTICE

- .github/workflows/check-build-test.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-nightly.yml
see https://github.com/apache/incubator-pekko/pull/1095
> upgrade CI actions

- build.sbt
- project/ResolverSettings.scala
> remove jcenter repo

- project/Dependencies.scala
- project/Versions.scala
> logback version

- project/Versions.scala
- project/build.properties
- project/plugins.sbt
- scripts/link-validator.conf
> upgrade build

- .git-blame-ignore-revs
relates to https://github.com/apache/pekko-connectors-kafka/pull/158
> fix commit for java fmt

- project/Versions.scala
example link
https://kafka.apache.org/37/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html
> link to Kafka 3.7 docs

- docs/src/main/paradox/release-notes/index.md
- docs/src/main/paradox/release-notes/releases-1.0.md
- docs/src/main/paradox/release-notes/releases-1.1.md
> add release notes for 1.1.0-M1

- docs/src/main/paradox/release-notes/index.md
* see #225 
* can't be cherry picked because the 1.0.x branch release notes are in a different format
> fix migration doc link (1.0.x)

- testkit/src/main/java/org/apache/pekko/kafka/testkit/internal/PekkoConnectorsKafkaContainer.java
- testkit/src/main/java/org/apache/pekko/kafka/testkit/internal/SchemaRegistryContainer.java
> getContainerIpAddress is deprecated

- .github/workflows/publish-1.1-docs.yml
- docs/src/main/paradox/release-notes/releases-1.1.md
> release notes for v1.1.0

- build.sbt
- project/Dependencies.scala
- project/ParadoxSettings.scala
- project/Versions.scala
https://github.com/pjfanning/sbt-pekko-build supports addPekkoModuleDependency which has tooling that supports testing with Pekko snaphots.
> use sbt-pekko-build addPekkoModuleDependency

- .github/workflows/check-build-test.yml
- .github/workflows/format.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
relates to #246  but I need ASF Infra team to approve the sbt/setup-sbt so this should get the CI working in the mean time
> CI: don't use ubuntu-latest

- .github/workflows/check-build-test.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-pekko.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
see https://github.com/apache/pekko-http/pull/619
> CI: setup-sbt

- docs/src/main/paradox/release-notes/releases-1.0.md
> fix broken akka link

- project/Versions.scala
> remove unused import

- README.md
* we run Mima checks on this repo as part of our CI
* I think we can say that are likely to retain good compatibility management in our releases
> remove caveat about bin compatibility

- docs/src/main/paradox/home.md
* recommend 3.7.1 due to CVE - https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients
* https://mvnrepository.com/artifact/org.apache.pekko/pekko-connectors-kafka_3/1.1.0 -- our last recent was built with 3.8.0
> doc: update kafka-client recommendation

- build.sbt
- project/ProjectSettings.scala
- project/plugins.sbt
jupiter-interface has moved org
> upgrade jupiter-interface

- .github/workflows/check-build-test.yml
- project/ProjectSettings.scala
- project/Versions.scala
> drop Scala 2.12 support
