apache/pekko-connectors-kafka

.github/workflows/format.yml
build.sbt

Similar to pekko core, replaces the sbt scalafmt check with a github actions one. Also removes the `scalafmtCheckAll`/`scalafmtSbtCheck` check because it is now unnecessary (and it also doesn't play well with IDE's).

Add github workflow to check scala code is formatted

---

README.md

`CONTRIBUTING.md` is pointing to the wrong repo. Furthermore there is no need to do a direct link, you can just use a relative path (as a bonus this means the link will continue to work even when this repo path will be updated, which it will be when pekko leaves incubation).

Fix README.md pointing to wrong CONTRIBUTING.md

---

.github/workflows/check-build-test.yml
tests/src/test/scala/org/apache/pekko/kafka/TransactionsOps.scala

When working on https://github.com/apache/incubator-pekko-connectors-kafka/pull/49 I forgot to add Scala 2.12 to build matrix

Add Scala 2.12 to matrix

---

.github/workflows/check-build-test.yml
benchmarks/src/main/scala/org/apache/pekko/kafka/benchmarks/Timed.scala
build.sbt
core/src/main/scala/org/apache/pekko/kafka/ConsumerMessage.scala
core/src/main/scala/org/apache/pekko/kafka/ProducerMessage.scala
core/src/main/scala/org/apache/pekko/kafka/internal/CommittingProducerSinkStage.scala
core/src/main/scala/org/apache/pekko/kafka/internal/DefaultProducerStage.scala
core/src/main/scala/org/apache/pekko/kafka/internal/DeferredProducer.scala
core/src/main/scala/org/apache/pekko/kafka/internal/KafkaConsumerActor.scala
core/src/main/scala/org/apache/pekko/kafka/internal/MessageBuilder.scala
core/src/main/scala/org/apache/pekko/kafka/scaladsl/DiscoverySupport.scala
project/Dependencies.scala
project/ParadoxSettings.scala
project/ProjectSettings.scala
project/Versions.scala
tests/src/test/scala/docs/scaladsl/ClusterShardingExample.scala
tests/src/test/scala/docs/scaladsl/FetchMetadata.scala
tests/src/test/scala/docs/scaladsl/proto/Order.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/CommittingProducerSinkSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/CommittingWithMockSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/ConsumerMock.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/ConsumerProgressTrackingSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/ConsumerSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/PartitionedSourceSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/internal/ProducerSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/javadsl/ControlSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/scaladsl/IntegrationSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/scaladsl/MetadataClientSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/scaladsl/RebalanceExtSpec.scala

* partial scala 3 build support
* code now compiles with Scala 3.2.2 but junit-vintage-engine is failing to run due to not liking some class names
* I've raised https://github.com/apache/incubator-pekko-connectors-kafka/issues/59 as a follow on
I've asked this question on the Scala Users forum: https://users.scala-lang.org/t/scala-3-compile-issue-code-that-compiles-in-scala-2-12-2-13/9246 -- edit: it looks like `private` is more strict in Scala 3 - I had to make some private constructors package private to fix compile.
I had to make quite a few code changes to get Scala 3 compilation to work

support scala 3 compilation

---

project/ProjectSettings.scala
project/plugins.sbt

Updates sbt-apache-sonatype. Note that this new version renames `SonatypeApachePlugin` to `ApacheSonatypePlugin` to be consistent with the project name.

Update sbt-apache-sonatype and handle rename

---

testkit/src/main/java/org/apache/pekko/kafka/testkit/KafkaTest.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/TestcontainersKafkaJunit4Test.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/TestcontainersKafkaTest.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/javadsl/BaseKafkaTest.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/javadsl/KafkaJunit4Test.java

When compiling this project you get these warnings
```
[warn] /Users/mdedetrich/github/incubator-pekko-connectors-kafka/testkit/src/main/java/org/apache/pekko/kafka/testkit/javadsl/BaseKafkaTest.java:49:1: org$apache$pekko$kafka$testkit$internal$KafkaTestKit$$adminDefaults() in org.apache.pekko.kafka.testkit.internal.KafkaTestKitClass implements org$apache$pekko$kafka$testkit$internal$KafkaTestKit$$adminDefaults() in org.apache.pekko.kafka.testkit.internal.KafkaTestKit
[warn]   return type requires unchecked conversion from java.util.Map to java.util.Map<java.lang.String,java.lang.Object>
[warn] public abstract class BaseKafkaTest extends KafkaTestKitClass {
```
Adding `@SuppressWarnings("unchecked")` solves these issues. Note that this is not unusual for Java code within Pekko projects …

Add suppress warnings for unchecked conversions

---

tests/src/it/scala/org/apache/pekko/kafka/PartitionedSourceFailoverSpec.scala

Unwraps single string interpolation i.e. `s"${something}"` into `s"$something"`. Make sure to do a rebase merge of this PR because I need to add its commit to `.git-blame-ignore-revs`

Unwrap single string interpolation syntax

---

build.sbt
project/ResolverSettings.scala
project/plugins.sbt

The Apache Snapshots nexus repo is sometimes giving us request refused, likely because we are overloading the repo with excessive amount of requests.  This is due to the fact that we are using `SNAPSHOT` versions which by default don't cache because they are mutable (i.e. you can reupload snapshots with different implementations as much as you like).
Since for both pekko and its project forks the snapshot version is derived from git hash, there is no disadvantage to caching the snapshot.

Cache snapshots to prevent overloading Apache Nexus repo

---

project/Dependencies.scala

* just a test dependency
* still want to match what scalapb uses - https://mvnrepository.com/artifact/com.thesamet.scalapb/scalapb-runtime_3/0.11.13
* https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java (no CVEs for 3.19.6)
* patch upgrade (from 3.19.1)

protobuf 3.19.6

---

README.md
build.sbt

* link to pekko docs
* add link to users mailing list
* remove the Software Mill logo - I don't think it is great for ASF projects to have commercial logos
* we do properly acknowledge Software Mill in the license file and source headers

add ref links to the README

---

core/src/main/scala/org/apache/pekko/kafka/ConsumerSettings.scala
core/src/main/scala/org/apache/pekko/kafka/ProducerSettings.scala
core/src/main/scala/org/apache/pekko/kafka/internal/ConfigSettings.scala
tests/src/test/scala/org/apache/pekko/kafka/ConsumerSettingsSpec.scala
tests/src/test/scala/org/apache/pekko/kafka/ProducerSettingsSpec.scala

Resolves: https://github.com/apache/incubator-pekko-connectors-kafka/issues/85
This PR reuses the upstream Kafka mechanism that is used to filter/mask passwords which means its 100% correct (the `.properties` fields being printed in `.toString` refers to configuration that is passed to proper Kafka). In more detail, Kafka has its own `org.apache.kafka.common.config.AbstractConfig` which actually maintains types for keys. One of those types is `kafka.common.config.ConfigDef.Type.PASSWORD` which is how upstream Kafka determines whether any sensitive field needs to be masked (see https://github.com/apache/kafka/blob/51bc41031b91b16ffcbd95832e8a20a00d3b6f81/clients/src/main/java/org/apache/kafka/common/config/types/Password.java#L54-L57 for more info).
Also note that this project already has …

Properly mask all sensitive fields in Consumer and Producer settings

---

core/src/main/resources/reference.conf
core/src/main/scala/org/apache/pekko/kafka/ConsumerMessage.scala
core/src/main/scala/org/apache/pekko/kafka/ConsumerSettings.scala
core/src/main/scala/org/apache/pekko/kafka/Metadata.scala
core/src/main/scala/org/apache/pekko/kafka/ProducerSettings.scala
core/src/main/scala/org/apache/pekko/kafka/RestrictedConsumer.scala
core/src/main/scala/org/apache/pekko/kafka/Subscriptions.scala
core/src/main/scala/org/apache/pekko/kafka/javadsl/MetadataClient.scala
core/src/main/scala/org/apache/pekko/kafka/javadsl/Producer.scala
core/src/main/scala/org/apache/pekko/kafka/javadsl/SendProducer.scala
core/src/main/scala/org/apache/pekko/kafka/scaladsl/Consumer.scala
core/src/main/scala/org/apache/pekko/kafka/scaladsl/MetadataClient.scala
core/src/main/scala/org/apache/pekko/kafka/scaladsl/Producer.scala
core/src/main/scala/org/apache/pekko/kafka/scaladsl/SendProducer.scala
testkit/src/main/java/org/apache/pekko/kafka/testkit/KafkaTest.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/TestcontainersKafkaJunit4Test.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/TestcontainersKafkaTest.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/javadsl/BaseKafkaTest.java
testkit/src/main/java/org/apache/pekko/kafka/testkit/javadsl/KafkaJunit4Test.java

Since the first pekko-connectors-kafka release is 1.0.0, we need to make sure that the alpakka-kafka version numbers in deprecation messages are explicit about the fact the version number is alpakka-kafka related.

add alpakka-kafka prefix to version numbers

---

LICENSE

* the LICENSE in https://github.com/apache/kafka/blob/trunk/LICENSE does not have a copyright so remove the line in our LICENSE
* there is a copyright in the Kafka NOTICE and we have that copied into our NOTICE
* was part of https://github.com/apache/incubator-pekko-connectors-kafka/pull/103 but this bit is possibly less contentious

remove copyright from kafka license

---

README.md

* basic build notes
* far from complete but possibly enough to tide over someone who just wants to basic build verification

add build docs

---

.github/workflows/check-build-test.yml
.github/workflows/format.yml
.github/workflows/headers.yml
.github/workflows/link-validator.yml
.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-nightly.yml

The latest version of the checkout github actions now supports a `fetch-tags` flag which does as described, i.e. it will fetch all of our tags which removes the various workarounds that was used before (i.e. manually running `git fetch` command) etc etc, see https://github.com/actions/checkout/pull/579
This will also help in the erroneous errors that we get in CI, i.e. 
```
[error] Failed to derive version from git tags. Maybe run `git fetch --unshallow` or `git fetch upstream` on a fresh git clone from a fork? Derived version: 0.0.0+1-337943bd-SNAPSHOT`
```

Use fetch tags from latest checkout action

---

project/Versions.scala

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-34917

kafka 3.0.2 due to CVE

---

build.sbt
project/plugins.sbt

Since we have a CVE which may require a release (see https://github.com/apache/incubator-pekko-connectors-kafka/pull/140) lets also fix the generated paradox doc/site so it can get released alongside with it.
If pekko-sbt-paradox gets released beforehand then its trivial to just update the version

Use latest pekko-sbt-paradox

---

.scala-steward.conf
project/Dependencies.scala

I am a Jackson contributor and Jackson 2.17.0 has a number of issues. In other Pekko modules, we have stuck with 2.16.x, for now.

pin to jackson 2.16

---

scripts/link-validator.conf

* has started causing link validation issues in a few pekko repos
* license report is where this link is now appearing

add asm.ow2.io exception in link validator

---

.github/workflows/check-build-test.yml
.github/workflows/nightly-pekko.yml
.github/workflows/nightly-pekko1.0.yml
project/PekkoCoreDependency.scala

* most pekko repos now use pekko 1.1 dependencies in main branch
* add nightly test run that checks code still works with pekko 1.0 libs

build with pekko 1.1

---

project/Versions.scala

we don't pin the kafka version

remove out of date comment in build

---

scripts/link-validator.conf

http link now appearing in license report - breaking link validator check

issue in license report

---

.github/workflows/check-build-test.yml

the checks in this CI job are needed for 1.0.x PRs - see #227 - this PR is blocked because this job did not run

allow check-build-test to run for 1.0.x branch

---

.github/workflows/link-validator.yml
scripts/link-validator.conf

see https://github.com/apache/pekko-management/pull/348

ignore broken links in license report

---

docs/src/main/paradox/serialization.md
testkit/src/main/resources/reference.conf
tests/src/test/scala/org/apache/pekko/kafka/scaladsl/RetentionPeriodSpec.scala

The docker images we test with are from Confluent. We are using old images.

test with latest available confluent images

---

LICENSE
testkit/src/main/java/org/apache/pekko/kafka/testkit/internal/PekkoConnectorsKafkaContainer.java

I noticed this line in the javadoc
https://github.com/apache/pekko-connectors-kafka/blob/3dda6f4fdcb46e3a5d5c30adfc4f7acb2a391173/testkit/src/main/java/org/apache/pekko/kafka/testkit/internal/PekkoConnectorsKafkaContainer.java#L32

add testcontainers ref to license

---

testkit/src/main/java/org/apache/pekko/kafka/testkit/internal/PekkoConnectorsKafkaContainer.java
testkit/src/main/resources/reference.conf
tests/src/test/scala/org/apache/pekko/kafka/scaladsl/RetentionPeriodSpec.scala

trying to test with newest Kafka releases - unfortunately, Confluent have not yet released a Kafka 4 based Confluent Docker releases.

Test with Confluent 7.9.0 docker images

---

.scala-steward.conf

Now that we no longer support java 8

Clean up dependency version pinning in config
